### ISSUE TITLE
Installed the latest repo repository.cguzzman-3.0.0.zip on Kodi 20, but still cannot install addons.

### ISSUE THREAD

**Issue by thelastfantasy** [cguZZman/repository.plugins#18]
Just reported on this issue
https://github.com/cguZZman/plugin.googledrive/issues/310#issuecomment-1399248072

**Comment by janglapuk** [comment]
> Just reported on this issue [cguZZman/plugin.googledrive#310 (comment)](https://github.com/cguZZman/plugin.googledrive/issues/310#issuecomment-1399248072)

The main Kodi repository is still serving the old version. [Google Drive](https://kodi.tv/addons/nexus/plugin.googledrive) plugin still shows **1.4.10+matrix.2**, and [Cloud Drive Common Module](https://kodi.tv/addons/nexus/script.module.clouddrive.common) shows **1.3.9+matrix.2**, instead of the latest one.

I still don't know if the information hasn't been updated by the author, or there is a delay in getting it updated to the Kodi database.

This solution can solve this problem by following the instructions given in the [README.md](https://github.com/cguZZman/repository.plugins/blob/master/README.md) in this repository by installing using **repo.daro.mx** source and selecting the latest version of addons repository (select **repository.cguzzman-3.0.0.zip** for Nexus).

Make sure to enabling "**Unknown Source**" and change "**Update official add-ons from**" option to "**Any repositories**" placed in **Settings / System / Add-ons** setting before doing the instructions.

**Comment by thelastfantasy** [comment]
Changed to "Any repositories" and successfully installed!
Thank you!

**Comment by janglapuk** [comment]
> Changed to "Any repositories" and successfully installed! Thank you!

You're welcome. Then you can close this issue.
